In [ ]:
from google.colab import files
import pandas as pd
import numpy as np
import nltk
nltk.download("punkt")
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('wordnet')

!pip install emoji
!pip install pyspellchecker

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


#LOADING THE DATA


In [ ]:
archive = files.upload()

Saving refined_ngram_dict.csv to refined_ngram_dict.csv
Saving labeled_data.csv to labeled_data.csv


# Preproceso


In [ ]:
df = pd.read_csv("labeled_data.csv",sep=",")
df

Unnamed: 0  ...                                              tweet
0               0  ...  !!! RT @mayasolovely: As a woman you shouldn't...
1               1  ...  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2               2  ...  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3               3  ...  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4               4  ...  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...           ...  ...                                                ...
24778       25291  ...  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779       25292  ...  you've gone and broke the wrong heart baby, an...
24780       25294  ...  young buck wanna eat!!.. dat nigguh like I ain...
24781       25295  ...              youu got wild bitches tellin you lies
24782       25296  ...  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 7 columns]

In [ ]:
tweets = df['tweet']

In [ ]:
import html
import emoji

def replace_emoji(tweet):
  tweet = emoji.demojize(html.unescape(tweet))
  return tweet

tweets = tweets.apply(replace_emoji)

In [ ]:
from nltk import word_tokenize

tokens = tweets
tokens = tokens.apply(word_tokenize)
tokens

0        [!, !, !, RT, @, mayasolovely, :, As, a, woman...
1        [!, !, !, !, !, RT, @, mleew17, :, boy, dats, ...
2        [!, !, !, !, !, !, !, RT, @, UrKindOfBrand, Da...
3        [!, !, !, !, !, !, !, !, !, RT, @, C_G_Anderso...
4        [!, !, !, !, !, !, !, !, !, !, !, !, !, RT, @,...
                               ...                        
24778    [you, 's, a, muthaf***in, lie, “, @, LifeAsKin...
24779    [you, 've, gone, and, broke, the, wrong, heart...
24780    [young, buck, wan, na, eat, !, !, .., dat, nig...
24781        [youu, got, wild, bitches, tellin, you, lies]
24782    [~~Ruffled, |, Ntac, Eileen, Dahlia, -, Beauti...
Name: tweet, Length: 24783, dtype: object

In [ ]:
from nltk.corpus import stopwords
en_stopw = set(stopwords.words('english'))

def clean_stopwords(tweet):
  lista = []
  for word in tweet: 
    if word not in en_stopw: 
      lista.append(word)
  return lista

tokens = tokens.apply(clean_stopwords)
tokens

0        [!, !, !, RT, @, mayasolovely, :, As, woman, n...
1        [!, !, !, !, !, RT, @, mleew17, :, boy, dats, ...
2        [!, !, !, !, !, !, !, RT, @, UrKindOfBrand, Da...
3        [!, !, !, !, !, !, !, !, !, RT, @, C_G_Anderso...
4        [!, !, !, !, !, !, !, !, !, !, !, !, !, RT, @,...
                               ...                        
24778    ['s, muthaf***in, lie, “, @, LifeAsKing, :, @,...
24779    ['ve, gone, broke, wrong, heart, baby, ,, drov...
24780    [young, buck, wan, na, eat, !, !, .., dat, nig...
24781             [youu, got, wild, bitches, tellin, lies]
24782    [~~Ruffled, |, Ntac, Eileen, Dahlia, -, Beauti...
Name: tweet, Length: 24783, dtype: object

In [ ]:
contractions = {'\'s':'is', '\'ve': 'have', 'n\'t':'not', '\'ll':'will', '\'re': 'are', '\'m': 'am'}


def remove_contractions(tweet):
  lista = []
  for word in tweet:
    if word in contractions:
      lista.append(contractions[word])
    else:
      lista.append(word)

  return lista

tokens = tokens.apply(remove_contractions)
tokens

0        [!, !, !, RT, @, mayasolovely, :, As, woman, n...
1        [!, !, !, !, !, RT, @, mleew17, :, boy, dats, ...
2        [!, !, !, !, !, !, !, RT, @, UrKindOfBrand, Da...
3        [!, !, !, !, !, !, !, !, !, RT, @, C_G_Anderso...
4        [!, !, !, !, !, !, !, !, !, !, !, !, !, RT, @,...
                               ...                        
24778    [is, muthaf***in, lie, “, @, LifeAsKing, :, @,...
24779    [have, gone, broke, wrong, heart, baby, ,, dro...
24780    [young, buck, wan, na, eat, !, !, .., dat, nig...
24781             [youu, got, wild, bitches, tellin, lies]
24782    [~~Ruffled, |, Ntac, Eileen, Dahlia, -, Beauti...
Name: tweet, Length: 24783, dtype: object

In [ ]:
unuseful = ['!', '"', '$', '%', '&', '/', '(', ')', '=', '_', '^', '*', '¡', '@', ':', ';', '#', 'RT', '.', '...']

def clean_unuseful(tweet):
  lista = []
  for word in tweet:
    if word not in unuseful:
      lista.append(word)
  return lista

tokens = tokens.apply(clean_unuseful)
tokens

0        [mayasolovely, As, woman, not, complain, clean...
1        [mleew17, boy, dats, cold, tyga, dwn, bad, cuf...
2        [UrKindOfBrand, Dawg, 80sbaby4life, You, ever,...
3           [C_G_Anderson, viva_based, look, like, tranny]
4        [ShenikaRoberts, The, shit, hear, might, true,...
                               ...                        
24778    [is, muthaf***in, lie, “, LifeAsKing, 20_Pearl...
24779    [have, gone, broke, wrong, heart, baby, ,, dro...
24780    [young, buck, wan, na, eat, .., dat, nigguh, l...
24781             [youu, got, wild, bitches, tellin, lies]
24782    [~~Ruffled, |, Ntac, Eileen, Dahlia, -, Beauti...
Name: tweet, Length: 24783, dtype: object

In [ ]:
def remove_capital(tweet):
  lista = []
  for word in tweet:
    lista.append(word.lower())
  return lista

tokens = tokens.apply(remove_capital)
tokens

0        [mayasolovely, as, woman, not, complain, clean...
1        [mleew17, boy, dats, cold, tyga, dwn, bad, cuf...
2        [urkindofbrand, dawg, 80sbaby4life, you, ever,...
3           [c_g_anderson, viva_based, look, like, tranny]
4        [shenikaroberts, the, shit, hear, might, true,...
                               ...                        
24778    [is, muthaf***in, lie, “, lifeasking, 20_pearl...
24779    [have, gone, broke, wrong, heart, baby, ,, dro...
24780    [young, buck, wan, na, eat, .., dat, nigguh, l...
24781             [youu, got, wild, bitches, tellin, lies]
24782    [~~ruffled, |, ntac, eileen, dahlia, -, beauti...
Name: tweet, Length: 24783, dtype: object

In [ ]:
#Very High time - Avoid execution

#Spell Corrector

'''from tqdm import tqdm
from spellchecker import SpellChecker

def correct_words(tweet):
  lista = []
  for word in tqdm(tweet):
      lista.append(spell.correction(word))
  return lista

spell = SpellChecker()
tokens = tokens.apply(correct_words)
tokens'''

In [ ]:
# Sacar palabra origen/comun

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def apply_lemmatize(tweet):
  return [lemmatizer.lemmatize(word) for word in tweet]

tokensLem = tokens.apply(apply_lemmatize)
tokensLem

0        [mayasolovely, a, woman, not, complain, cleani...
1        [mleew17, boy, dat, cold, tyga, dwn, bad, cuff...
2        [urkindofbrand, dawg, 80sbaby4life, you, ever,...
3           [c_g_anderson, viva_based, look, like, tranny]
4        [shenikaroberts, the, shit, hear, might, true,...
                               ...                        
24778    [is, muthaf***in, lie, “, lifeasking, 20_pearl...
24779    [have, gone, broke, wrong, heart, baby, ,, dro...
24780    [young, buck, wan, na, eat, .., dat, nigguh, l...
24781                [youu, got, wild, bitch, tellin, lie]
24782    [~~ruffled, |, ntac, eileen, dahlia, -, beauti...
Name: tweet, Length: 24783, dtype: object

In [ ]:
# Reducir a raiz

from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

def apply_stemmer(t):
  return [stemmer.stem(word) for word in t]

tokensStem = tokens.apply(apply_stemmer)
tokensStem

0        [mayasolov, as, woman, not, complain, clean, h...
1        [mleew17, boy, dat, cold, tyga, dwn, bad, cuff...
2        [urkindofbrand, dawg, 80sbaby4lif, you, ever, ...
3             [c_g_anderson, viva_bas, look, like, tranni]
4        [shenikarobert, the, shit, hear, might, true, ...
                               ...                        
24778    [is, muthaf***in, lie, “, lifeask, 20_pearl, c...
24779    [have, gone, broke, wrong, heart, babi, ,, dro...
24780    [young, buck, wan, na, eat, .., dat, nigguh, l...
24781                [youu, got, wild, bitch, tellin, lie]
24782    [~~ruffl, |, ntac, eileen, dahlia, -, beauti, ...
Name: tweet, Length: 24783, dtype: object

# Vectorization

In [ ]:
from nltk.tokenize import sent_tokenize

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(min_df=1)

X = vectorizer.fit_transform(sent_tokenize(' '.join(tokens[0])))

print(vectorizer.vocabulary_)
print(X.toarray())

{'mayasolovely': 6, 'as': 1, 'woman': 10, 'not': 7, 'complain': 3, 'cleaning': 2, 'house': 4, 'man': 5, 'always': 0, 'take': 8, 'trash': 9}
[[1 1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# TFIDF

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize
from tqdm.notebook import tqdm

vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=1)

vectorized_tweets = []

for tweet in tqdm(tokens):
  X = vectorizer.fit_transform(sent_tokenize(' '.join(tweet)))

  pos_vocab = {v:i for i, v in enumerate(vectorizer.get_feature_names())}

  tfidf = X.toarray()

  vectorized_tweets.append(tfidf)

[array([[0.21821789, 0.21821789, 0.21821789, 0.21821789, 0.21821789,
         0.21821789, 0.21821789, 0.21821789, 0.21821789, 0.21821789,
         0.21821789, 0.21821789, 0.21821789, 0.21821789, 0.21821789,
         0.21821789, 0.21821789, 0.21821789, 0.21821789, 0.21821789,
         0.21821789]]),
 array([[0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
         0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
         0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
         0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
         0.20851441, 0.20851441, 0.20851441]]),
 array([[0.24613641, 0.24613641, 0.24613641, 0.24613641, 0.        ,
         0.        , 0.24613641, 0.24613641, 0.24613641, 0.24613641,
         0.24613641, 0.24613641, 0.24613641, 0.        , 0.24613641,
         0.24613641, 0.24613641, 0.24613641, 0.17512809, 0.        ,
         0.24613641],
        [0.        , 0.        , 0.        , 0.        , 0.47107781,
         

In [ ]:
# N-Grams

In [ ]:
# POS

def apply_tagging(t):
  return nltk.pos_tag(t)

tags = tokens.apply(apply_tagging)
tags

0        [(mayasolovely, RB), (as, IN), (woman, NN), (n...
1        [(mleew17, NN), (boy, NN), (dats, NNS), (cold,...
2        [(urkindofbrand, NN), (dawg, VBZ), (80sbaby4li...
3        [(c_g_anderson, NN), (viva_based, VBD), (look,...
4        [(shenikaroberts, NNS), (the, DT), (shit, NN),...
                               ...                        
24778    [(is, VBZ), (muthaf***in, JJ), (lie, JJ), (“, ...
24779    [(have, VB), (gone, VBN), (broke, RB), (wrong,...
24780    [(young, JJ), (buck, NN), (wan, WP), (na, TO),...
24781    [(youu, NN), (got, VBD), (wild, JJ), (bitches,...
24782    [(~~ruffled, VBN), (|, JJ), (ntac, NN), (eilee...
Name: tweet, Length: 24783, dtype: object

# Feature selection

In [ ]:
df_vector = df[['hate_speech', 'offensive_language', 'neither', 'class']]
df_vector['tweet'] = vectorized_tweets
df_vector

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


hate_speech  ...                                              tweet
0                0  ...  [[0.2182178902359924, 0.2182178902359924, 0.21...
1                0  ...  [[0.20851441405707477, 0.20851441405707477, 0....
2                0  ...  [[0.24613641459392016, 0.24613641459392016, 0....
3                0  ...  [[0.3333333333333333, 0.3333333333333333, 0.33...
4                0  ...  [[0.20851441405707477, 0.20851441405707477, 0....
...            ...  ...                                                ...
24778            0  ...  [[0.19999999999999998, 0.19999999999999998, 0....
24779            0  ...  [[0.24253562503633297, 0.24253562503633297, 0....
24780            0  ...  [[0.2182178902359924, 0.2182178902359924, 0.21...
24781            0  ...  [[0.30151134457776363, 0.30151134457776363, 0....
24782            0  ...  [[0.18569533817705186, 0.18569533817705186, 0....

[24783 rows x 5 columns]

In [ ]:
from sklearn.feature_selection import SelectKBest, chi2, f_regression

df_final = df_vector[['hate_speech', 'offensive_language','neither', 'tweet', 'class']]

X_df = df_final.iloc[:,0:4]
Y_df = df_final.iloc[:,4] #class column

X_df_new = SelectKBest(score_func=chi2,k=1).fit_transform(X_df,Y_df)

print(X_df_new)

ValueError: ignored